// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLFdJjnyjcgAoHVnZgkhu3zzY26ljHeg',
    appId: '1:996721668582:web:4d5088cf8a835d0dda2627',
    messagingSenderId: '996721668582',
    projectId: 'burger-house-80541',
    authDomain: 'burger-house-80541.firebaseapp.com',
    storageBucket: 'burger-house-80541.firebasestorage.app',
    measurementId: 'G-KX95J9BRL3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn_1j-EWQ5hukK4agbiQLnvOh9gvfus1w',
    appId: '1:996721668582:android:d3c6256aac4aba4ada2627',
    messagingSenderId: '996721668582',
    projectId: 'burger-house-80541',
    storageBucket: 'burger-house-80541.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tYhKIP5nTTpiUEwJcN1zojLtu69CYYM',
    appId: '1:996721668582:ios:0929687f5988cec8da2627',
    messagingSenderId: '996721668582',
    projectId: 'burger-house-80541',
    storageBucket: 'burger-house-80541.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tYhKIP5nTTpiUEwJcN1zojLtu69CYYM',
    appId: '1:996721668582:ios:0929687f5988cec8da2627',
    messagingSenderId: '996721668582',
    projectId: 'burger-house-80541',
    storageBucket: 'burger-house-80541.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtLFdJjnyjcgAoHVnZgkhu3zzY26ljHeg',
    appId: '1:996721668582:web:43425332853eae3bda2627',
    messagingSenderId: '996721668582',
    projectId: 'burger-house-80541',
    authDomain: 'burger-house-80541.firebaseapp.com',
    storageBucket: 'burger-house-80541.firebasestorage.app',
    measurementId: 'G-K37CTDN2Q4',
  );
}
