# flutter_stripe 12.1.x exposes optional push-provisioning bridges from its
# Android dependency. Hungry Spot does not offer push provisioning, so these
# optional classes are intentionally absent. Keep R8 strict for every other
# missing type while suppressing only the rules generated by AGP.
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivity$g
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Args
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter$Error
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningActivityStarter
-dontwarn com.stripe.android.pushProvisioning.PushProvisioningEphemeralKeyProvider
